### PR TITLE
Moving average utility - addresses #3

### PR DESCRIPTION
**Pull request by jmason42**
This adds a utility function to perform a moving average on stochastic simulation output.  I think there are other sorts of data reductions that could be applied, and this code is far from optimal, but it satisfies a basic need.

Additionally I restructured the package a bit.  This new function lives in `arrow.analysis.distributions` while the plotting function lives in `arrow.analysis.plotting`.  In addition to conceptually organizing these utilities, the latter will allow for isolation of the matplotlib dependency.  I'm not committed to this organization - for example, we could flatten things out and place both submodules at the main level of the package.

Demonstration:
moving_average

### CODE REVIEW

**Comment by jmason42** [comment]
@prismofeverything Was it your intention to run the complexation test twice, or was that to address the issue (which is now fixed via 9cfbe7859290eaa82b3a88635af4fd5fdf604d41) with the wrong number of axes showing up?

**Comment by prismofeverything** [comment]
> @prismofeverything Was it your intention to run the complexation test twice, or was that to address the issue (which is now fixed via 9cfbe78) with the wrong number of axes showing up?

Ah, it was kind of both! Thanks for fixing that issue with the axes : ) I wanted to compare two runs to each other out of my own curiosity, but if the axis issue is fixed and I know it is working we can just run it once. Along those lines I think we could add a few more systems to fill it out. 

I realize also I have just been pushing to master, I'll cast my changes from here on out as PR's like this one. Thanks John!

**Comment by prismofeverything** [comment]
As far as this PR, looks good! I am happy to merge if you feel it is ready.

**Comment by jmason42** [comment]
I'll go ahead and merge it.  Push to master if you like, it really doesn't perturb me.  I will probably stick to PRs and just merge them regularly, although for urgent (and thoroughly tested) bugfixes, or non-coding changes (docstrings etc.) I may push directly to master.

**Pull request merged**
