### PR TITLE
Removed support for alternate forms, rearranging tests to allow for profiling

### PR DESCRIPTION
**Pull request by prismofeverything**

### CODE REVIEW

**Comment by jmason42** [comment]
This will be helpful.  Incidentally I played with Numba a bit and got mixed results.  I think we can start JIT'ing `choose` and `propensity` but `step` and `evolve` pose a number of issues

**Comment by prismofeverything** [comment]
I saw something similar, yet overall runtime is still lower without `jit`ing anything.... which is weird. Might try cython next, or I might just write this in C.

**Comment by jmason42** [comment]
> I saw something similar, yet overall runtime is still lower without jiting anything.... which is weird. Might try cython next, or I might just write this in C.

That's odd.  I was getting 3x speed-ups when JIT'ing those two functions.

**Comment by prismofeverything** [comment]
Alright I'll try it with the full sim and see what happens.

**Pull request merged**
